## System of Linear Equations

**After this assigment you will be able to:**
* Use `NumPy` packages to set up arrays corresponding to the system of linear equations.
* Evaluate the determinant of a matrix and find the solution of the system with `NumPy` linear algebra package.
* Perform row reduction to bring matrix into row echelon from.
* Find the solution for the system of linear equations using row reduced matrix.

### Packages

In [1]:
import numpy as np

Load the unit test defined specifically for this notebook

In [4]:
import w2_unittest

### 1 - System of Linear Equations and Corresponding `NumPy` Arrays

Matrices can be used to solve systems of equations. But first, you need to represent the system using matrices. Given the following system of linear equations:

$$\begin{cases}
2x_1 - x_2 + x_3 + x_4 = 6, \\
x_1 + 2x_2 - x_3 - x_4 = 3, \\
-x_1 + 2x_2 + 2x_3 + 2x_4 = 14, \\
x_1 - x_2 + 2x_3 + x_4 = 8,
\end{cases}\tag{1}$$

you will construct a matrix $A$, where each row represents one equation in the system and each column represents a variable $x_1$,$x_2$,$x_3$,$x_4$. The free coefficient from the right sides of the equations you will put in a vector $b$

##### Exercise 1

Construct matrix $A$ and vector $b$ corresponding to the system of linear equations $(1)$

In [7]:
A = np.array([
  [2, -1, 1, 1],
  [1, 2, -1, -1],
  [-1, 2, 2, 2],
  [1, -1, 2, 1]
], dtype = np.dtype(float))

b = np.array([6, 3, 14, 8], dtype = np.dtype(float))

print(A)
print(b)

[[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [-1.  2.  2.  2.]
 [ 1. -1.  2.  1.]]
[ 6.  3. 14.  8.]


In [8]:
w2_unittest.test_matrix(A, b)

 All tests passed


### 2 - Solution for the System of Equations with `NumPy` Linear Algebra Package

A system of four linear equations with four unknown variables has a unique solution if and only if the determinant of the corresponding matrix of coefficients is not equal to zero.

#### Exercise 2

Find the determinant $d$ of matrix A and the solution vector $x$ for the system of linear equation $(1)$.

In [14]:
# Find the determinant of matrix A
d_A = np.linalg.det(A)
print(f"{d_A:.2f}")

-17.00


In [15]:
# Find the solution of vector x for the system of linear equation
x = np.linalg.solve(A, b)
print(x)

[2. 3. 4. 1.]


In [18]:
# test my solution
w2_unittest.test_det_and_solution_scipy(d_A, x)

 All tests passed


### 3 - Elementary Operations and Row Reduction

Here you will solve the system of linear equations algebraically using row reduction. It envolves combination of the equations using elementary operations, eliminaring as many variables as possible for each equation. There are three valid operations which can be performed to bring the system of equations to equivalent one (with the same solutions):

* Multiply any row by non-zero number
* Add tow rows and exchange one of the original rows with the result of the addition.
* Swap rows

#### Exercise 3

Set up three functions corresponding to the discussed above elementary operations.

In [ ]:
def MultiplyRow(M, row_num, row_num_multiple):
  # .copy() is required here to keep the original matrix without any changes
  M_new = M.copy()

  