In [2]:
import numpy as np

In [3]:
# 1-D array
one_dim_arr = np.array([1, 2, 3, 4, 5, 6])

# Multidimensional array using reshape()
multi_dim_array = np.reshape(one_dim_arr, (2, 3))

### 2.1 - Finding size, shape and dimension.

In future assigments, you will need to know how to find the size, dimension and shape of an array, These are all attributes of a `ndarray` and can be accessed as follows:

* `ndarray.ndim` - Stores the number dimension of the array.
* `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.
* `ndarray.size` - Stores the number of elements in the array

In [4]:
#  Dimension of the 2-D array multi_dim_arr
multi_dim_array.ndim

2

In [5]:
# shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
multi_dim_array.shape

(2, 3)

In [6]:
# Size of the array multi_dim_arr
# Returns total number of elements
multi_dim_array.size

6

## 3 - Array math operations

In [7]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


### 3.1 - Multiplying vector with a scalar (broadcasting)

Suppose you need to convert miles to kilometers. To do so, you can use the Numpy array function that you have learned so far.

You can do this by carrying out an operation between an array (miles) and a single number (the conversion rate which is a scalar). Since 1 mile = 1.6 km, Numpy coputes each multiplication within each cell.

This concept is called `broadcasting`, which allows you to perform operations specifically on arrays of different shapes.

In [8]:
vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

## 4 - Indexing and slicing

Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you will see in future assigments for multidimensional arrays.

### 4.1 - Indexing

Let us select specific elements from the arry as given.

In [9]:
# Select the third element of the array. Remember the counting starts from 0
a = ([1, 2, 3, 4, 5, 6])
print(a[2])

# Select the first element of the array
print(a[0])

3
1


For multidimensional arrays of shape `n`, to index a specific element, you must input `n` indices, one for each dimension.

In [10]:
# Indexing on a 2-D array
two_dim = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select element number 8 from the 2-D array using indices i, j
print(two_dim[2][1])

8


### 4.2 - Slicing

Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive).

The sixtax is:

* `array[start:end:step]`

If no value is passed to start, it is assumed `start = 0`, if no value is passed to end, it is assumed that `end = length of array - 1` and if no value is passed to step, it is assumed `step = 1`

In [11]:
# Slice the array a to get the array [2, 3, 4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [12]:
# Slice the array a to get the array [1, 2, 3]
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [13]:
# Slice the array a to get [3, 4, 5]
slice_arr = a[2:-1]
print(slice_arr)

[3, 4, 5]


In [14]:
# Slice the array a to get the array [1,3,5]
slice_arr = a[::2]
print(slice_arr)

[1, 3, 5]


In [15]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

True


In [16]:
# Slice the two_dim array to get the first two rows
slice_arra_1 = two_dim[:2]
print(slice_arra_1)

[[1 2 3]
 [4 5 6]]


In [17]:
# Similarily, slice the two_dim array to get the last two rows
slice_arr_1 = two_dim[1:]
print(slice_arr_1)

[[4 5 6]
 [7 8 9]]


In [18]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


## 5 - Stacking

Finally, stacking is a feature of NumPy that leads to increased customization of arrays, It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis.

* `np.vstack()` - stacks vertically
* `np.hstack()` - stacks horizontally
* `np.hsplit()` - splits an array into several smaller arrays

In [19]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])

In [20]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [21]:
# stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
