## numpy.diag

Extract a diagonal or construct a diagonal array.

Parameters:

> `v` : array_like
>> If `v` is a 2 dimensional array, return a copy of its k-th diagonal.
>> If `v` is a 1 dimensional array, return a 2 dimensional array with `v` on the k-th diagonal

> `k` : int (optional)
>> Diagonal in question. The default is 0. Use `k > 0` for diagonals above the main diagonal. And `k < 0` for diagonals below

## numpy.unravel_index

Converts a flat index or array of flat indices into a tuple of coordinate arrays.

Parameters:

> `indices` : array_like
>> An integer array whose elements are indices into the flattened version of an array of dimensions shape.

> `shape` : tuple of ints
>> The shape of the array to use for unraveling indices

> `order` : {'C', 'F'} optional

In [106]:
import numpy as np

# 2D matrix
matrix = np.random.randint(1, 30, size = (4, 4))

# indice
positions_to_findout = [1, 4]

# Original matrix
print("Original Matrix")
print(matrix)

# Guardamos los indices que queremos buscar
my_indices = np.unravel_index(positions_to_findout, matrix.shape)
print(my_indices)

# Valor del primer elemento a buscar
print(f"Valores de la primera posicion {my_indices[0]}")
print(matrix[my_indices[0][0]][my_indices[0][1]])

# Valor del segundo elemento a buscar
print(f"Valores de la segunda posicion {my_indices[1]}")
print(matrix[my_indices[1][0]][my_indices[1][1]])


Original Matrix
[[22  8  1 14]
 [20 23 26 11]
 [15 27 20 22]
 [29  2 10 20]]
(array([0, 1]), array([1, 0]))
Valores de la primera posicion [0 1]
8
Valores de la segunda posicion [1 0]
20


## numpy.tile

Construct an array by repeating A the number of times given by reps

Parameters:

> `A` : array_like
>> The input array.

> `reps` : array_like
>> The number of representations of A along each axis.

In [ ]:
# array
a = np.array([1, 0])
b = np.array([0, 1])

# matrix 8x8
checkerboard = np.tile(A = [a, b], reps = (4, 4))

print(checkerboard)

## numpy.dtype

Create a data type object

Parameters : 

> `dtype`
>> Object to be converted to a data type object

> `align` : bool, optional

> `copy` : bool, optional

> `metadata` : dict, optional